---
abstract: 'Access Perl subs via command line'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200007, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sub-Spec-CmdLine
requires:
  Capture::Tiny: 0
  Data::Clone: 0
  Data::Dump::Partial: 0
  Data::Format::Pretty: 0
  Data::Format::Pretty::Console: 0
  Data::Format::Pretty::JSON: 0
  Data::Format::Pretty::PHPSerialization: 0
  Data::Format::Pretty::YAML: 0
  JSON: 0
  List::MoreUtils: 0
  Log::Any: 0
  Sub::Spec: 0.04
  Sub::Spec::BashComplete: 0.15
  Sub::Spec::GetArgs::Argv: 0.04
  Sub::Spec::Runner: 0.18
  Test::More: 0.96
  perl: 5.010000
resources:
  homepage: http://search.cpan.org/dist/Sub-Spec-CmdLine/
  repository: http://github.com/sharyanto/perl-Sub-Spec-CmdLine
version: 0.35
