---
abstract: 'Access Perl subs via command line'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200003, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sub-Spec-CmdLine
requires:
  Capture::Tiny: 0
  Clone::Any: 0
  Data::Dump::Partial: 0
  Data::Format::Pretty::Console: 0
  JSON: 0
  List::MoreUtils: 0
  Log::Any: 0
  PHP::Serialization: 0
  YAML::Syck: 0
  perl: 5.010000
resources:
  homepage: http://search.cpan.org/dist/Sub-Spec-CmdLine/
  repository: http://github.com/sharyanto/perl-Sub-Spec-CmdLine
version: 0.14
